package model;

public interface SQLSalaryUpdate {
  public final String SQL_GET_EMPLOYEES = 
    "SELECT E.EMPLOYEE_ID, E.LAST_NAME || ', ' || E.FIRST_NAME AS EMPLOYEE_NAME,D.DEPARTMENT_ID, J.JOB_TITLE, E.SALARY, E.MANAGER_ID\n" +
    "FROM EMPLOYEES E, DEPARTMENTS D, JOBS J\n" +
    "WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.JOB_ID = J.JOB_ID AND E.MANAGER_ID IS NOT NULL\n" +
    "UNION\n" +
    "SELECT E2.EMPLOYEE_ID, E2.LAST_NAME || ', ' || E2.FIRST_NAME AS EMPLOYEE_NAME, -1 AS DEPARTMENT_ID, J2.JOB_TITLE, E2.SALARY, E2.MANAGER_ID\n" +
    "FROM EMPLOYEES E2, JOBS J2\n" +
    "WHERE E2.DEPARTMENT_ID IS NULL AND E2.JOB_ID = J2.JOB_ID\n" +
    "UNION\n" +
    "SELECT E.EMPLOYEE_ID, E.LAST_NAME || ', ' || E.FIRST_NAME AS EMPLOYEE_NAME,D.DEPARTMENT_ID, J.JOB_TITLE, E.SALARY, -1 AS MANAGER_ID\n" +
    "FROM EMPLOYEES E, DEPARTMENTS D, JOBS J\n" +
    "WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.JOB_ID = J.JOB_ID AND E.MANAGER_ID IS NULL\n" +
    "ORDER BY EMPLOYEE_NAME";
	
  public final String SQL_GET_JOBS =
    "SELECT JOB_TITLE, JOB_ID\n" +
    "FROM\n" +
    "  (SELECT J.JOB_ID, J.JOB_TITLE, COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT\n" +
    "   FROM JOBS J, EMPLOYEES E\n" +
    "   WHERE J.JOB_ID = E.JOB_ID\n" +
    "   GROUP BY J.JOB_ID, J.JOB_TITLE)\n" +
    "WHERE EMPLOYEE_COUNT > 0\n" +
    "ORDER BY JOB_TITLE";
	
  public final String SQL_GET_DEPARTMENTS = 
    "SELECT DEPARTMENT_NAME, DEPARTMENT_ID, EMPLOYEE_COUNT\n" +
    "FROM\n" +
    "  (SELECT D.DEPARTMENT_ID, D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT\n" +
    "   FROM DEPARTMENTS D, EMPLOYEES E\n" +
    "   WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID\n" +
    "   GROUP BY D.DEPARTMENT_ID, D.DEPARTMENT_NAME)\n" + 
    "WHERE EMPLOYEE_COUNT > 0\n" +
    "ORDER BY DEPARTMENT_NAME";
  
  public final String SQL_GET_MANAGERS = 
    "SELECT M.LAST_NAME || ', ' || M.FIRST_NAME AS MANAGER_NAME, E.MANAGER_ID\n" +
    "FROM EMPLOYEES E, EMPLOYEES M\n" +   
    "WHERE E.MANAGER_ID = M.EMPLOYEE_ID\n" +
    "GROUP BY M.LAST_NAME || ', ' || M.FIRST_NAME, E.MANAGER_ID\n" +
    "ORDER BY MANAGER_NAME";
  
  public final String SQL_UPDATE_SALARY_PART1 = 
    "UPDATE EMPLOYEES\n" +
          
    "SET SALARY = ";
  public final String SQL_UPDATE_SALARY_PART2 =
    "\n" +
    "WHERE EMPLOYEE_ID = ";  
}
